# Generated by Django 3.0 on 2021-02-21 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_haiku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haiku',
            name='user',
        ),
        migrations.AddField(
            model_name='haiku',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='haiku', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
