# Generated by Django 3.0 on 2021-02-21 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210221_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='haiku',
            old_name='five1',
            new_name='fiveone',
        ),
        migrations.RenameField(
            model_name='haiku',
            old_name='five2',
            new_name='fivetwo',
        ),
    ]
