# Generated by Django 3.0 on 2021-02-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210222_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haiku',
            name='fiveone',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='haiku',
            name='fivetwo',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='haiku',
            name='seven',
            field=models.CharField(max_length=24),
        ),
    ]
