# Generated by Django 3.0 on 2021-02-22 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210222_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haiku',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haikus', to=settings.AUTH_USER_MODEL),
        ),
    ]
