# Generated by Django 3.0 on 2021-02-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210222_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='haiku',
            name='title',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
